import { Inter } from 'next/font/google'
import './globals.css'
import ResponsiveAppBar from '@/components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Inventory Management system',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ResponsiveAppBar />
                {children}
            </body>
        </html>
    )
}
